name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      docker:
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true docker-react npm run test
    
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to Elastic Beanstalk
          uses: einaregilsson/beanstalk-deploy@v14
          with:
            region: "us-east-1"
            app_name: "frontend"
            env_name: "Frontend-env"
            bucket_name: "elasticbeanstalk-us-east-1-403127866524"
            bucket_path: "frontend"
            access_key: ${{ secrets.AWS_ACCESS_KEY }}
            secret_key: ${{ secrets.AWS_SECRET_KEY }}